Fixed URL, former domain is now for sale
takanabe/react-redux-material_ui-boilerplate pull request #17
Opened 2016-10-21 06:56 UTC by nicolas-raoul

New URL found in the description fields at https://github.com/reduxframework/redux-framework
+ minor grammar fixes

2016-12-02 05:41 UTC, JLHwung requested changes

2016-12-02 05:41 UTC, JLHwung commented on README.md
> +* [Redux](https://reduxframework.com/)
Redux framework is a Wordpress framework, see http://redux.js.org

2017-01-15 16:25 UTC, takanabe commented on README.md
> +* [Redux](https://reduxframework.com/)
@nicolas-raoul  please modify url to the correct one, then I will merge this PR.

2017-01-16 01:56 UTC, nicolas-raoul commented
Sorry for the delay, is it better now?

2017-01-16 13:03 UTC, takanabe commented
Thanks!

2017-01-16 13:03 UTC, merged